### ISSUE TITLE
Design idea

### ISSUE THREAD

**Issue by scart88** [mrsked/mrsk-site#1]
Here is a design idea for the MRSK website.

![mrsk-test](https://user-images.githubusercontent.com/84858745/217246566-7c822a49-3bdf-4cee-84a1-b00844e5b181.jpg)

I just discovered https://sitepress.cc 
@dhh do you have any thoughts about it?

**Comment by dhh** [comment]
Appreciate the attempt! Going to work with Sean, the designer of rubyonrails.org, on coming up with something a bit more unique.
